apiVersion: v2
name: traefik-hub
description: Traefik Hub Ingress Controller
type: application
version: 5.0.0-rc.1
# renovate: image=ghcr.io/traefik/traefik-hub
appVersion: v2.10.0
kubeVersion: ">=1.24.0-0"
keywords:
  - traefik
  - ingress
  - networking
  - api
  - apimanagement
home: https://traefik.io/traefik-hub
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: mmatur
    email: michael.matur@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
icon: https://doc.traefik.io/traefik-hub/assets/images/logos-traefik-hub-horizontal.svg
annotations:
  artifacthub.io/changes: |
    - "feat: add option to update image pull policy"
    - "feat: traefik v3 upgrade"
    - "feat: add ingressroute for dashboard options"
    - "feat: remove sidecar mode"
    - "chore: update CRDs to v1.0.0"
